spring:
  application:
    name: game-auto-script-poster

poster:
  # 应用名
  app: poster
  # 应用版本号
  version: 1.3
  # 应用显示坐标-X
  location-x: 725
  # 应用显示坐标-Y
  location-y: 357
  # 应用最大运行时长, 单位: 秒
  # 该参数值必须大于599, 不然不会生效
  run-max-time: -1
  # 达到最大运行时长后, 是否自动关机
  # ON[自动关机], OFF[关闭程序]
  auto-shutdown: OFF
  # 窗口标题
  title:
  # 后台脚本的图片地址
  backend-img-path:
  # 前台脚本的图片地址
  font-img-path:
  # 缩放比例
  scaling: 1.0
  # 脚本效率, 单位: 毫秒
  efficiency: 1000
  # 鼠标单击的最小耗时
  click-space-min: 100
  # 鼠标单击的最大耗时
  click-space-max: 300
  # 脚本没有动作的最大时长, 单位: 秒
  # 当脚本长时间没有操作时, 会播放音乐
  no-action-max-time: 300
